# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_data.proto',
  package='SensorData',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11sensor_data.proto\x12\nSensorData\"3\n\x0fSensorDataEntry\x12\x11\n\ttime_span\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\";\n\x0eSensorDataList\x12)\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1b.SensorData.SensorDataEntryb\x06proto3'
)




_SENSORDATAENTRY = _descriptor.Descriptor(
  name='SensorDataEntry',
  full_name='SensorData.SensorDataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_span', full_name='SensorData.SensorDataEntry.time_span', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='SensorData.SensorDataEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=84,
)


_SENSORDATALIST = _descriptor.Descriptor(
  name='SensorDataList',
  full_name='SensorData.SensorDataList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SensorData.SensorDataList.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=145,
)

_SENSORDATALIST.fields_by_name['data'].message_type = _SENSORDATAENTRY
DESCRIPTOR.message_types_by_name['SensorDataEntry'] = _SENSORDATAENTRY
DESCRIPTOR.message_types_by_name['SensorDataList'] = _SENSORDATALIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorDataEntry = _reflection.GeneratedProtocolMessageType('SensorDataEntry', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDATAENTRY,
  '__module__' : 'sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:SensorData.SensorDataEntry)
  })
_sym_db.RegisterMessage(SensorDataEntry)

SensorDataList = _reflection.GeneratedProtocolMessageType('SensorDataList', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDATALIST,
  '__module__' : 'sensor_data_pb2'
  # @@protoc_insertion_point(class_scope:SensorData.SensorDataList)
  })
_sym_db.RegisterMessage(SensorDataList)


# @@protoc_insertion_point(module_scope)
